Add example to show usage of functions set_pin, change_pin, unlock_pin and verify_pin
Infineon/BlockchainSecurity2Go-Python-Library pull request #13
Opened 2019-08-07 11:54 UTC by DhruvKhemani

This example includes a python script showing how to create and modify PIN codes on the Blockchain Security 2Go card. It also includes a documentation explaining how the program uses these functions.

The documentation does make a reference to a folder that hasnt been published yet but will be in the future. This was done on purpose sothat I dont have to create a pull request in future to change 1 line of code.

2019-08-07 13:47 UTC, ahoeller commented on examples/modify-pin/README.md
> +* [set_pin](#set_pin-command) - Sets a new PIN code
I would propose using the term "PIN value" instead of "PIN code" as it can be everything like a password and does not need to be a number

2019-08-07 13:48 UTC, ahoeller commented on examples/modify-pin/README.md
> +* [unlock_pin](#unlock_pin-command) - Removes PIN code using the corresponding PUK
"Removing PIN code" might be misleading. I would phrase it like "Deactivating the PIN authentication..."

2019-08-07 13:48 UTC, ahoeller commented on examples/modify-pin/README.md
> +* [verify_pin](#verify_pin-command) - Verifies a PIN code and enables the `generate_signature` command
AFAIK also the import-key feature requires a PIN

2019-08-07 13:49 UTC, ahoeller commented on examples/modify-pin/README.md
> +The contents of `get_reader()` and `activate_card(reader)` have already been covered in the previous example [get-card-info](../get-card-info). Please reference that example if something is unclear i
...reference to...

2019-08-09 06:56 UTC, ahoeller commented on examples/modify-pin/README.md
> +Note that if the card already has a PIN, then executing this line will return an error.
Please add a note that in our implementation the PIN is UTF-8 encoded (e.g. for the pin 1234 the "PIN bytes" 31:32:33:34 will be sent to the card)

2019-08-09 06:58 UTC, ahoeller commented on examples/modify-pin/README.md
> +The `change_pin(reader, old_pin, new_pin)` command is used to change the current PIN value on the Blockchain Security 2Go card with a new PIN value. Same as with the [set_pin](#set_pin-command) comma
... change ... to...

2019-08-09 07:06 UTC, ahoeller commented on examples/modify-pin/README.md
> +Keep in mind that having no PIN is unsecure and therefore it is strongly recommended that you always have a PIN enabled.
Please be careful with such statements. When having no PIN the card is not "unsecure" it is just less secure than with PIN :)

2019-08-09 07:10 UTC, ahoeller commented on examples/modify-pin/README.md
> +The functions [change_pin](#change_pin-command) and [unlock_pin](#unlock_pin-command) can be used together to reset the PIN if for example the PIN value on the card is known but the PUK is lost:
This is what the unlock_pin cli command does. IMHO it would be sufficient to refer to disable_pin.py

2019-08-09 07:20 UTC, ahoeller requested changes
Thank you for the easy to understand example. Please consider the in-line comments for the README.md file.

2019-08-09 13:35 UTC, DhruvKhemani commented
Updated the README.md with all of your suggested improvements :)

2019-08-13 07:09 UTC, merged